update

diff --git a/bin/vitisenv-exec b/bin/vitisenv-exec
--- a/bin/vitisenv-exec
+++ b/bin/vitisenv-exec
@@ -6,14 +6,17 @@ fi
 
 CMD_NAME=`basename $0`
 if [ "$CMD_NAME" = vitisenv-exec ]; then
-  echo "vitisenv-exec cannot be called directly"
-  exit 1
+#  echo "vitisenv-exec cannot be called directly"
+#  exit 1
+  CMD_NAME=$1
+  shift 1
 fi
 
-VERSION_FILE=`vitisenv-version-file`
-VITIS_VERSION=`cat $VERSION_FILE`
+VITIS_VERSION=`vitisenv-version`
 SETTING_FILE=$XILINX_INSTALL_DIR/Vitis/$VITIS_VERSION/settings64.sh
 if [ -e $SETTING_FILE ]; then
   source $SETTING_FILE
   $CMD_NAME $@
+else
+  echo "$SETTING_FILE is not found."
 fi
